app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
fos_user_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix: /admin
