<?php

namespace AppBundle\Entity\Repository;

/**
 * DiscountNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountNewsRepository extends \Doctrine\ORM\EntityRepository
{
}
