<?php

namespace AppBundle\Entity\Repository;

/**
 * NewsPictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsPictureRepository extends \Doctrine\ORM\EntityRepository
{
}
