<?php

namespace AppBundle\Entity\Repository;

/**
 * UserNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserNewsRepository extends \Doctrine\ORM\EntityRepository
{
}
