<?php

namespace AppBundle\Entity\Repository;

/**
 * UserNewsViewCounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserNewsViewCounterRepository extends \Doctrine\ORM\EntityRepository
{
}
