<?php

namespace AppBundle\Entity\Repository;

/**
 * ViewCounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewCounterRepository extends \Doctrine\ORM\EntityRepository
{
}
