<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VKGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VKGroupRepository extends EntityRepository
{
    public function getNext(){
        $qb = $this->createQueryBuilder('g')
            ->orderBy('g.requested_date', 'ASC')
            ->where('g.deleted=0')
            ->setMaxResults(1);

        return $qb->getQuery()->execute();
    }

    public function getGroupsByCategories(array $categories){
        $qb = $this->createQueryBuilder('g');
        $qb->leftJoin('g.category', 'category')
            ->where($qb->expr()->in('category.indentity', $categories));

        $qb->orderBy('category.title');

        return $qb;
    }

    public function getGroupsFormMainPage(){
        $qb = $this->getGroupsByCategories(array('news', 'news_sport', 'traveling', 'afisha'));

        return $qb->getQuery()->execute();
    }

    public function getGroupsCategory($category){
        $qb = $this->getGroupsByCategories(array($category));

        return $qb->getQuery()->execute();
    }

    public function getAllGroup()
    {
        $qb = $this->createQueryBuilder('g');
        $qb->leftJoin('g.category', 'category')
            ->where('g.deleted=0');

        $qb->orderBy('category.title');

        return $qb->getQuery()->execute();
    }
}
