<?php

namespace AppBundle\Entity\Repository\Information;

/**
 * AdditionalInfo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditionalInfo extends \Doctrine\ORM\EntityRepository
{
    public function getInformation(array $fields)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->where($qb->expr()->in('a.param_name', $fields));

        return $qb->getQuery()->execute();
    }
}
