<?php

namespace AppBundle\Entity\Repository\Interview;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteVisitNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
