<?php

namespace AppBundle\Entity\Repository\Traffic;

/**
 * ZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneRepository extends \Doctrine\ORM\EntityRepository
{
    public function getZones()
    {
        $qb = $this->createQueryBuilder('z')
            ->select('z', 'r')
            ->leftJoin('z.routes', 'r');

        return $qb->getQuery()->execute();
    }
}
